QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    Camera.cpp \
    Model.cpp \
    RenderTarget.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3AlignedAllocator.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Logging.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Vector3.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3ConvexHullComputer.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3GeometryUtil.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Raycast/b3GpuRaycast.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.cpp \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3Solver.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBoxShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConeShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMiniSDF.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btSdfCollisionShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btShapeHull.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btSphereShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btContactProcessing.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactBvh.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactShape.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_box_set.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_contact.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_memory.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_tri_collision.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Character/btKinematicCharacterController.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btBatchedConstraints.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btRigidBody.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBody.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    SDKs/bullet3-3.22a/src/BulletDynamics/Vehicle/btWheelInfo.cpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDMath.cpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/MultiBodyTree.cpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/MultiBodyTreeImpl.cpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDefaultSoftBodySolver.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableBackwardEulerObjective.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableBodySolver.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableContactConstraint.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableContactProjection.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMultiBodyConstraintSolver.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBody.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyHelpers.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/poly34.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/TaskScheduler/btTaskScheduler.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/TaskScheduler/btThreadSupportPosix.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/TaskScheduler/btThreadSupportWin32.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btAlignedAllocator.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btConvexHull.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btConvexHullComputer.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btGeometryUtil.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btPolarDecomposition.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btQuickprof.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btReducedVector.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btSerializer.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btSerializer64.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btThreads.cpp \
    SDKs/bullet3-3.22a/src/LinearMath/btVector3.cpp \
    SDKs/bullet3-3.22a/src/btBulletCollisionAll.cpp \
    SDKs/bullet3-3.22a/src/btBulletDynamicsAll.cpp \
    SDKs/bullet3-3.22a/src/btLinearMathAll.cpp \
    SDKs/bullet3-3.22a/src/clew/clew.c \
    Shader.cpp \
    Texture.cpp \
    main.cpp \
    mainwindow.cpp \
    skybox.cpp

HEADERS += \
    Camera.h \
    Model.h \
    RenderTarget.h \
    SDKs/bullet3-3.22a/examples/CommonInterfaces/CommonFileIOInterface.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    SDKs/bullet3-3.22a/src/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3AlignedAllocator.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3AlignedObjectArray.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3CommandLineArgs.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3FileUtils.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3HashMap.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Logging.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Matrix3x3.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3MinMax.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3PoolAllocator.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3QuadWord.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Quaternion.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Random.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3ResizablePool.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Scalar.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3StackAlloc.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Transform.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3TransformUtil.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/b3Vector3.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3Float4.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3Int2.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3Int4.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3Mat3x3.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3PlatformDefinitions.h \
    SDKs/bullet3-3.22a/src/Bullet3Common/shared/b3Quat.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/shared/b3Inertia.h \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3AabbUtil.h \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3ConvexHullComputer.h \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3GeometryUtil.h \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuBroadphaseInterface.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/b3SapAabb.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/gridBroadphaseKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/parallelLinearBvhKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/sapKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Initialize/b3OpenCLInclude.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Initialize/b3OpenCLUtils.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3BvhInfo.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3ConvexPolyhedronCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3SupportMappings.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3VectorFloat4.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/mprKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satConcaveKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3BufferInfoCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3FillCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3OpenCLArray.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernelsCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernelsCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernelsCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsFloat4CL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32KernelsCL.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Raycast/b3GpuRaycast.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Raycast/kernels/rayCastKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuConstraint4.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuNarrowPhaseInternalData.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipelineInternalData.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuSolverBody.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3GpuSolverConstraint.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/b3Solver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/batchingKernels.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/integrateKernel.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/jointSolver.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solveContact.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solveFriction.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverSetup.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverSetup2.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverUtils.h \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btAxisSweep3Internal.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDbvt.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btDispatcher.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    SDKs/bullet3-3.22a/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionObject.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btGhostObject.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btManifoldResult.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionDispatch/btUnionFind.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBox2dShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBoxShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCapsuleShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCollisionMargin.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCollisionShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCompoundShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConcaveShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConeShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvex2dShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexHullShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btCylinderShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btEmptyShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMaterial.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMiniSDF.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btSdfCollisionShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btShapeHull.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btSphereShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleCallback.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleMesh.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btTriangleShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btBoxCollision.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btClipPolygon.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btContactProcessing.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btContactProcessingStructs.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactBvh.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactBvhStructs.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactMassUtil.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactQuantizedBvhStructs.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGImpactShape.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btGeometryOperations.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btQuantization.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/btTriangleShapeEx.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_array.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_bitset.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_box_collision.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_box_set.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_clip_polygon.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_contact.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_geom_types.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_geometry.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_hash_table.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_linear_math.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_math.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_memory.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_pair.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_radixsort.h \
    SDKs/bullet3-3.22a/src/BulletCollision/Gimpact/gim_tri_collision.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btMprPenetration.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    SDKs/bullet3-3.22a/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Character/btCharacterControllerInterface.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Character/btKinematicCharacterController.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btBatchedConstraints.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSolverBody.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btActionInterface.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btRigidBody.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBody.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyInplaceSolverIslandCallback.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyJointFeedback.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyLink.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Vehicle/btRaycastVehicle.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    SDKs/bullet3-3.22a/src/BulletDynamics/Vehicle/btWheelInfo.h \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDConfig.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDConfigBuiltin.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDConfigEigen.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDErrorMessages.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/IDMath.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/MultiBodyTree.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/IDEigenInterface.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/IDLinearMathInterface.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/IDMatVec.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/MultiBodyTreeImpl.hpp \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/DeformableBodyInplaceSolverIslandCallback.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btCGProjection.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btConjugateGradient.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btConjugateResidual.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDefaultSoftBodySolver.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableBackwardEulerObjective.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableBodySolver.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableContactConstraint.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableContactProjection.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableCorotatedForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableGravityForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableLagrangianForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableLinearElasticityForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMassSpringForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMousePickingForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMultiBodyConstraintSolver.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btDeformableNeoHookeanForce.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btKrylovSolver.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btPreconditioner.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBody.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyData.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyHelpers.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyInternals.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftBodySolvers.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/btSparseSDF.h \
    SDKs/bullet3-3.22a/src/BulletSoftBody/poly34.h \
    SDKs/bullet3-3.22a/src/LinearMath/TaskScheduler/btThreadSupportInterface.h \
    SDKs/bullet3-3.22a/src/LinearMath/btAabbUtil2.h \
    SDKs/bullet3-3.22a/src/LinearMath/btAlignedAllocator.h \
    SDKs/bullet3-3.22a/src/LinearMath/btAlignedObjectArray.h \
    SDKs/bullet3-3.22a/src/LinearMath/btConvexHull.h \
    SDKs/bullet3-3.22a/src/LinearMath/btConvexHullComputer.h \
    SDKs/bullet3-3.22a/src/LinearMath/btCpuFeatureUtility.h \
    SDKs/bullet3-3.22a/src/LinearMath/btDefaultMotionState.h \
    SDKs/bullet3-3.22a/src/LinearMath/btGeometryUtil.h \
    SDKs/bullet3-3.22a/src/LinearMath/btGrahamScan2dConvexHull.h \
    SDKs/bullet3-3.22a/src/LinearMath/btHashMap.h \
    SDKs/bullet3-3.22a/src/LinearMath/btIDebugDraw.h \
    SDKs/bullet3-3.22a/src/LinearMath/btImplicitQRSVD.h \
    SDKs/bullet3-3.22a/src/LinearMath/btList.h \
    SDKs/bullet3-3.22a/src/LinearMath/btMatrix3x3.h \
    SDKs/bullet3-3.22a/src/LinearMath/btMatrixX.h \
    SDKs/bullet3-3.22a/src/LinearMath/btMinMax.h \
    SDKs/bullet3-3.22a/src/LinearMath/btModifiedGramSchmidt.h \
    SDKs/bullet3-3.22a/src/LinearMath/btMotionState.h \
    SDKs/bullet3-3.22a/src/LinearMath/btPolarDecomposition.h \
    SDKs/bullet3-3.22a/src/LinearMath/btPoolAllocator.h \
    SDKs/bullet3-3.22a/src/LinearMath/btQuadWord.h \
    SDKs/bullet3-3.22a/src/LinearMath/btQuaternion.h \
    SDKs/bullet3-3.22a/src/LinearMath/btQuickprof.h \
    SDKs/bullet3-3.22a/src/LinearMath/btRandom.h \
    SDKs/bullet3-3.22a/src/LinearMath/btReducedVector.h \
    SDKs/bullet3-3.22a/src/LinearMath/btScalar.h \
    SDKs/bullet3-3.22a/src/LinearMath/btSerializer.h \
    SDKs/bullet3-3.22a/src/LinearMath/btSpatialAlgebra.h \
    SDKs/bullet3-3.22a/src/LinearMath/btStackAlloc.h \
    SDKs/bullet3-3.22a/src/LinearMath/btThreads.h \
    SDKs/bullet3-3.22a/src/LinearMath/btTransform.h \
    SDKs/bullet3-3.22a/src/LinearMath/btTransformUtil.h \
    SDKs/bullet3-3.22a/src/LinearMath/btVector3.h \
    SDKs/bullet3-3.22a/src/btBulletCollisionCommon.h \
    SDKs/bullet3-3.22a/src/btBulletDynamicsCommon.h \
    SDKs/bullet3-3.22a/src/clew/clew.h \
    Shader.h \
    Texture.h \
    mainwindow.h \
    skybox.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

INCLUDEPATH += $$PWD/SDKs/bullet3-3.22a/src
DEPENDPATH += $$PWD/SDKs/bullet3-3.22a/src
DEFINES += BT_THREADSAFE=1 B3_USE_CLEW B3_USE_SSE BT_USE_SSE_IN_API

win32: LIBS += -L$$PWD/SDKs/Assimp/lib/ -lassimp -lIrrXML -lzlib
INCLUDEPATH += $$PWD/SDKs/Assimp/include
DEPENDPATH += $$PWD/SDKs/Assimp/include

INCLUDEPATH += $$PWD/SDKs/glm/include
DEPENDPATH += $$PWD/SDKs/glm/include

win32: LIBS += -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32
win32: LIBS += -lopengl32 -lglu32

win32: LIBS += -L$$PWD/SDKs/glew-2.1.0/lib/ -lglew32
INCLUDEPATH += $$PWD/SDKs/glew-2.1.0/include
DEPENDPATH += $$PWD/SDKs/glew-2.1.0/include

win32: LIBS += -L$$PWD/SDKs/FreeImage/lib/ -lFreeImage
INCLUDEPATH += $$PWD/SDKs/FreeImage/include
DEPENDPATH += $$PWD/SDKs/FreeImage/include

win32: LIBS += -L$$PWD/SDKs/OpenAL/lib/ -lOpenAL32
INCLUDEPATH += $$PWD/SDKs/OpenAL/include
DEPENDPATH += $$PWD/SDKs/OpenAL/include

win32: LIBS += -L$$PWD/SDKs/FreeALUT/lib/ -lalut
INCLUDEPATH += $$PWD/SDKs/FreeALUT/include
DEPENDPATH += $$PWD/SDKs/FreeALUT/include

RESOURCES += \
    resource.qrc

DISTFILES += \
    SDKs/bullet3-3.22a/src/Bullet3Collision/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3Collision/premake4.lua \
    SDKs/bullet3-3.22a/src/Bullet3Common/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3Common/premake4.lua \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3Dynamics/premake4.lua \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3Geometry/premake4.lua \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/gridBroadphase.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/parallelLinearBvh.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/BroadphaseCollision/kernels/sap.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/mpr.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/sat.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/NarrowphaseCollision/kernels/satConcave.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanFloat4Kernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32Kernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/Raycast/kernels/rayCastKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/batchingKernels.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/integrateKernel.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/jointSolver.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solveContact.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solveFriction.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverSetup.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverSetup2.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/solverUtils.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.cl \
    SDKs/bullet3-3.22a/src/Bullet3OpenCL/premake4.lua \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/Bullet3Serialize/Bullet2FileLoader/premake4.lua \
    SDKs/bullet3-3.22a/src/BulletCollision/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/BulletCollision/premake4.lua \
    SDKs/bullet3-3.22a/src/BulletDynamics/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/BulletDynamics/premake4.lua \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/BulletInverseDynamics/premake4.lua \
    SDKs/bullet3-3.22a/src/BulletSoftBody/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/BulletSoftBody/premake4.lua \
    SDKs/bullet3-3.22a/src/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/LinearMath/CMakeLists.txt \
    SDKs/bullet3-3.22a/src/LinearMath/premake4.lua
